shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_item, name='item'),
    path('<int:item_id>/', views.detail_item, name='detail'),
    path('greetings/', views.greetings),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
]

shop/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField('Наименование товара', max_length=30)
    price = models.IntegerField('Цена товара')

    def __str__(self):
        return f'{self.name} - {self.price}'


class Purchase(models.Model):
    name = models.CharField('ФИО клиента', max_length=30)
    age = models.IntegerField('Возраст клиента')
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    date_purchase = models.DateTimeField('Дата покупки')

    def __str__(self):
        return f'{self.name} - {self.age}'

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Item, Purchase


def greetings(request):
    return HttpResponse('Добро пожаловать в наш магазин!')


def list_item(request):
    items = Item.objects.all()
    return render(request, 'index.html', {'item_list': items})


def detail_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    context = {'item': item}
    return render(request, 'detail.html', context)

shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список напитков</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

shop/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<form action="#" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ item.name }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for purchase in item.purchase_set.all %}
        <label>{{ purchase.name }}</label><br>
    {% endfor %}
</fieldset>
</form>
{% endblock content %}

shop/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h2 class="mt-5 mb-5 text-center">Прайс-лист</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Напиток</th>
      <th scope="col">Цена</th>
      <th scope="col">Действия</th>
    </tr>
  </thead>
  <tbody>
  {% if item_list %}
    <ul>
    {% for item in item_list %}
    <tr>
      <th scope="row">{{ item.id }}</th>
      <td>{{ item.name }}</td>
      <td>{{ item.price }}</td>
      <td><a href="{% url 'detail' item.id %}">Подробнее</a></td>
    </tr>
  {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
  </tbody>
</table>
{% endblock content %}